[package]
name = "simpleuid"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "simpleuid"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.31"
pyo3 = "0.19.0"
rand = "0.8.5"
